### PR TITLE
Minor copy edit

### PR DESCRIPTION
**Pull request by bas-ie**
I struggle a bit with the phrasing of:

> It makes me thoroughly sad - and angry - thinking about how much average state education is missing the mark.

I feel like it 'buries the lead' a little. Maybe:

> Most state education is missing the mark by a wide margin. It makes me thoroughly sad - and angry.

### CODE REVIEW

**Comment by dominictarr** [comment]
[bury the _lede_](http://grammarist.com/usage/lead-lede/)

**Comment by bas-ie** [comment]
http://howardowens.com/lede-vs-lead/ ;)

**Comment by dominictarr** [comment]
hmm, it's beginning to seem like journalists just love inventing new spellings?
https://en.wikipedia.org/wiki/Nut_graph

**Comment by bas-ie** [comment]
o.O there's gotta be more where that came from...

**Comment by mixmix** [comment]
@richchurcher thanks so much for those fixes !

**Pull request merged**
